### ISSUE TITLE
How can I shorten the spaces between the numbers ? By default, it is too wide to me.

### ISSUE THREAD

**Issue by bigship** [jonathantribouharet/JTNumberScrollAnimatedView#6]

**Comment by jonathantribouharet** [comment]
There is no space, the labels are autosized to all have the same width depending of the width of `JTNumberScrollAnimatedView`, if you want to change the width (and so reduce the space between numbers) you just have to reduce the width of the `JTNumberScrollAnimatedView`.

**Comment by bigship** [comment]
@jonathantribouharet Thanks. Setting a width constraint to `JTNumberScrollAnimatedView` and manipulate it at runtime works. Issue closed.
